---
- name: restart_app
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  ansible.builtin.systemd:
    name: "{{ item.service_name }}"
    state: restarted
  with_items:
    - { service_name: "{{ deployment_service }}" }
    # - { service_name: "{{ deployment_service_2 }}" }
    # - { service_name: "{{ deployment_service_3 }}" }
